{
 "title": "Servidores - Proxmox",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "PVE1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "PVE2" },
     "item": { "filter": "Proxmox: Node [pve2]: Status" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total de Memória",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE2" },
     "item": {
      "filter": "Proxmox: Node [pve2]: Memory, total"
     },
     "itemTag": { "filter": "component: memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memória Disponível",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "$hosts" },
     "item": {
      "filter": "Proxmox: Node [pve2]: Memory, Disponível"
     },
     "itemTag": { "filter": "component: memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU - PVE1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "$hosts" },
     "item": {
      "filter": "Proxmox: Node [pve2]: CPU, usage"
     },
     "itemTag": { "filter": "component: cpu" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de Memória  - PVE1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "$hosts" },
     "item": {
      "filter": "Proxmox: Node [pve2]: Memory, used"
     },
     "itemTag": { "filter": "component: memory" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status das VMs no PVE - PROXMOX",
   "type": "stat",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:267",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "PVE1: Proxmox: VM",
        "VM"
       ],
       "text": "replaceAlias(PVE1: Proxmox: VM, VM)"
      }
     ],
     "host": { "filter": "$hosts" },
     "item": { "filter": "/.Uptime*/" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage Sistema - PVE1",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:206",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Sistema - Utilizado" ],
       "text": "setAlias(Storage Sistema - Utilizado)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE2" },
     "item": {
      "filter": "Proxmox: Storage [pve2/local]: Used"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:227",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Sistema - Disponível" ],
       "text": "setAlias(Storage Sistema - Disponível)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE2" },
     "item": {
      "filter": "Proxmox: Storage [pve2/local]: Disponível"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:248",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Sistema - Total" ],
       "text": "setAlias(Storage Sistema - Total)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "$hosts" },
     "item": {
      "filter": "Proxmox: Storage [pve2/local]: Size"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage Bunker1 - PVE2",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:39",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Bunker1 - Utilizado" ],
       "text": "setAlias(Storage Bunker1 - Utilizado)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE2" },
     "item": {
      "filter": "Proxmox: Storage [pve2/Bunker1]: Used"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:60",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Bunker1 - Disponível" ],
       "text": "setAlias(Storage Bunker1 - Disponível)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE2" },
     "item": {
      "filter": "Proxmox: Storage [pve2/Bunker1]: Disponível"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:86",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Bunker1 - Total" ],
       "text": "setAlias(Storage Bunker1 - Total)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE2" },
     "item": {
      "filter": "Proxmox: Storage [pve2/Bunker1]: Size"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage Backup - PVE1",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:457",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Backup - Utilizado" ],
       "text": "setAlias(Storage Backup - Utilizado)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE1" },
     "item": {
      "filter": "Proxmox: Storage [server1/hd-bkp01]: Used"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:478",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Backup - Disponível" ],
       "text": "setAlias(Storage Backup - Disponível)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE1" },
     "item": {
      "filter": "Proxmox: Storage [server1/hd-bkp01]: Disponível"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:499",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Storage Backup - Total" ],
       "text": "setAlias(Storage Backup - Total)"
      }
     ],
     "group": { "filter": "Hypervisors" },
     "host": { "filter": "PVE1" },
     "item": {
      "filter": "Proxmox: Storage [server1/hd-bkp01]: Size"
     },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}